#!/usr/bin/env bash

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

rm ~/.local/bin/solcompile
rm ~/.local/bin/solrun

ln -sf $DIR/scripts/solcompile.sh "$HOME"/.local/bin/solcompile 
ln -sf $DIR/scripts/solrun.sh "$HOME"/.local/bin/solrun

